In [128]:
import pandas as pd
import numpy as np

## Import the yearly data

In [129]:
data_2015= pd.read_csv("2015.csv")
data_2016= pd.read_csv("2016.csv")
data_2017= pd.read_csv("2017.csv")
data_2018= pd.read_csv("2018.csv")
data_2019= pd.read_csv("2019.csv")
data_2020= pd.read_csv("2020.csv")
data_2021= pd.read_csv("2021.csv")
data_2022= pd.read_csv("2022.csv")

## Add year column before combining them

In [130]:
data_2015["Year"]=2015
data_2016["Year"]=2016
data_2017["Year"]=2017
data_2018["Year"]=2018
data_2019["Year"]=2019
data_2022["Year"]=2022

## Understand the data element and uniform the data before append

In [131]:
data_2015.head(3)

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual,Year
0,Switzerland,Western Europe,1,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738,2015
1,Iceland,Western Europe,2,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201,2015
2,Denmark,Western Europe,3,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204,2015

In [132]:
#data_2015.head()
data_2016.head(3)

,Country,Region,Happiness Rank,Happiness Score,Lower Confidence Interval,Upper Confidence Interval,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual,Year
0,Denmark,Western Europe,1,7.526,7.460,7.592,1.44178,1.16374,0.79504,0.57941,0.44453,0.36171,2.73939,2016
1,Switzerland,Western Europe,2,7.509,7.428,7.590,1.52733,1.14524,0.86303,0.58557,0.41203,0.28083,2.69463,2016
2,Iceland,Western Europe,3,7.501,7.333,7.669,1.42666,1.18326,0.86733,0.56624,0.14975,0.47678,2.83137,2016

In [133]:
data_2017=data_2017.rename(columns={"Happiness.Score":"Happiness Score","Happiness.Rank": "Happiness Rank", "Economy..GDP.per.Capita.": "Economy (GDP per Capita)", "Health..Life.Expectancy.": "Health (Life Expectancy)","Trust..Government.Corruption.":"Trust (Government Corruption)","Dystopia.Residual":"Dystopia Residual"})
data_2017.head(3)

,Country,Region,Happiness Rank,Happiness Score,Whisker.high,Whisker.low,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Generosity,Trust (Government Corruption),Dystopia Residual,Year
0,Norway,Western Europe,1,7.537,7.594445,7.479556,1.616463,1.533524,0.796667,0.635423,0.362012,0.315964,2.277027,2017
1,Denmark,Western Europe,2,7.522,7.581728,7.462272,1.482383,1.551122,0.792566,0.626007,0.355280,0.400770,2.313707,2017
2,Iceland,Western Europe,3,7.504,7.622030,7.385970,1.480633,1.610574,0.833552,0.627163,0.475540,0.153527,2.322715,2017

In [134]:
data_2018=data_2018.rename(columns={"Social support":"Family","Freedom to make life choices":"Freedom","Score":"Happiness Score","Country or region":"Country","Overall rank": "Happiness Rank", "GDP per capita": "Economy (GDP per Capita)", "Healthy life expectancy": "Health (Life Expectancy)","Perceptions of corruption":"Trust (Government Corruption)"})
data_2018.head(3)

,Happiness Rank,Country,Region,Happiness Score,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Generosity,Trust (Government Corruption),Dystopia Residual,Year
0,1,Finland,Western Europe,7.632,1.305,1.592,0.874,0.681,0.202,0.393,2.585,2018
1,2,Norway,Western Europe,7.594,1.456,1.582,0.861,0.686,0.286,0.340,2.383,2018
2,3,Denmark,Western Europe,7.555,1.351,1.590,0.868,0.683,0.284,0.408,2.371,2018

In [135]:
data_2019=data_2019.rename(columns={"Freedom to make life choices":"Freedom","Social support":"Family","Score":"Happiness Score","Country or region":"Country","Overall rank": "Happiness Rank", "GDP per capita": "Economy (GDP per Capita)", "Healthy life expectancy": "Health (Life Expectancy)","Perceptions of corruption":"Trust (Government Corruption)"})
data_2019.head(3)

,Happiness Rank,Country,Region,Happiness Score,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Generosity,Trust (Government Corruption),Dystopia Residual,Year
0,1,Finland,Western Europe,7.769,1.340,1.587,0.986,0.596,0.153,0.393,2.714,2019
1,2,Denmark,Western Europe,7.600,1.383,1.573,0.996,0.592,0.252,0.410,2.394,2019
2,3,Norway,Western Europe,7.554,1.488,1.582,1.028,0.603,0.271,0.341,2.241,2019

In [136]:
data_2020.head(3)
list(data_2020.columns)

['Happiness Rank',
 'Country',
 'Region',
 'Happiness Score',
 'Economy (GDP per Capita)',
 'Family',
 'Health (Life Expectancy)',
 'Freedom',
 'Generosity',
 'Trust (Government Corruption)',
 'Dystopia Residual',
 'Year']

In [137]:
data_2021.head(3)

,Happiness Rank,Country,Region,Happiness Score,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Generosity,Trust (Government Corruption),Dystopia Residual,Year
0,1,Finland,Western Europe,7.842,1.446,1.106,0.741,0.691,0.124,0.481,3.253,2021
1,2,Denmark,Western Europe,7.620,1.502,1.108,0.763,0.686,0.208,0.485,2.868,2021
2,3,Switzerland,Western Europe,7.571,1.566,1.079,0.816,0.653,0.204,0.413,2.839,2021

In [138]:
list(data_2015.columns)

['Country',
 'Region',
 'Happiness Rank',
 'Happiness Score',
 'Standard Error',
 'Economy (GDP per Capita)',
 'Family',
 'Health (Life Expectancy)',
 'Freedom',
 'Trust (Government Corruption)',
 'Generosity',
 'Dystopia Residual',
 'Year']

In [139]:
list(data_2016.columns)

['Country',
 'Region',
 'Happiness Rank',
 'Happiness Score',
 'Lower Confidence Interval',
 'Upper Confidence Interval',
 'Economy (GDP per Capita)',
 'Family',
 'Health (Life Expectancy)',
 'Freedom',
 'Trust (Government Corruption)',
 'Generosity',
 'Dystopia Residual',
 'Year']

In [140]:
list(data_2017.columns)

['Country',
 'Region',
 'Happiness Rank',
 'Happiness Score',
 'Whisker.high',
 'Whisker.low',
 'Economy (GDP per Capita)',
 'Family',
 'Health (Life Expectancy)',
 'Freedom',
 'Generosity',
 'Trust (Government Corruption)',
 'Dystopia Residual',
 'Year']

In [141]:
list(data_2018.columns)

['Happiness Rank',
 'Country',
 'Region',
 'Happiness Score',
 'Economy (GDP per Capita)',
 'Family',
 'Health (Life Expectancy)',
 'Freedom',
 'Generosity',
 'Trust (Government Corruption)',
 'Dystopia Residual',
 'Year']

In [142]:
list(data_2020.columns)

['Happiness Rank',
 'Country',
 'Region',
 'Happiness Score',
 'Economy (GDP per Capita)',
 'Family',
 'Health (Life Expectancy)',
 'Freedom',
 'Generosity',
 'Trust (Government Corruption)',
 'Dystopia Residual',
 'Year']

In [143]:

data_2022=data_2022.rename(columns={"Happiness score":"Happiness Score","RANK":"Happiness Rank"})
list(data_2022.columns)

['Happiness Rank',
 'Country',
 'Region',
 'Happiness Score',
 'Dystopia Residual',
 'Economy (GDP per Capita)',
 'Family',
 'Health (Life Expectancy)',
 'Freedom',
 'Generosity',
 'Trust (Government Corruption)',
 'Year']

In [144]:
df_all = data_2015.append([data_2016,data_2017,data_2018,data_2019,data_2020,data_2021,data_2022],ignore_index = True)

In [145]:
df_all.head(5)

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual,Year,Lower Confidence Interval,Upper Confidence Interval,Whisker.high,Whisker.low
0,Switzerland,Western Europe,1,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738,2015,NaN,NaN,NaN,NaN
1,Iceland,Western Europe,2,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201,2015,NaN,NaN,NaN,NaN
2,Denmark,Western Europe,3,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204,2015,NaN,NaN,NaN,NaN
3,Norway,Western Europe,4,7.522,0.03880,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531,2015,NaN,NaN,NaN,NaN
4,Canada,North America,5,7.427,0.03553,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176,2015,NaN,NaN,NaN,NaN

In [146]:
data2020=df_all[df_all['Year']==2020]
data2020

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual,Year,Lower Confidence Interval,Upper Confidence Interval,Whisker.high,Whisker.low
782,Finland,Western Europe,1,7.8087,NaN,1.285190,1.499526,0.961271,0.662317,0.477857,0.159670,2.762835,2020,NaN,NaN,NaN,NaN
783,Denmark,Western Europe,2,7.6456,NaN,1.326949,1.503449,0.979333,0.665040,0.495260,0.242793,2.432741,2020,NaN,NaN,NaN,NaN
784,Switzerland,Western Europe,3,7.5599,NaN,1.390774,1.472403,1.040533,0.628954,0.407946,0.269056,2.350267,2020,NaN,NaN,NaN,NaN
785,Iceland,Western Europe,4,7.5045,NaN,1.326502,1.547567,1.000843,0.661981,0.144541,0.362330,2.460688,2020,NaN,NaN,NaN,NaN
786,Norway,Western Europe,5,7.4880,NaN,1.424207,1.495173,1.008072,0.670201,0.434101,0.287985,2.168266,2020,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
930,Central African Republic,Sub-Saharan Africa,149,3.4759,NaN,0.041072,0.000000,0.000000,0.292814,0.028265,0.253513,2.860198,2020,NaN,NaN,NaN,NaN
931,Rwanda,Sub-Saharan Africa,150,3.3123,NaN,0.343243,0.522876,0.572383,0.604088,0.485542,0.235705,0.548445,2020,NaN,NaN,NaN,NaN
932,Zimbabwe,Sub-Saharan Africa,151,3.2992,NaN,0.425564,1.047835,0.375038,0.377405,0.080929,0.151349,0.841031,2020,NaN,NaN,NaN,NaN
933,South Sudan,Sub-Saharan Africa,152,2.8166,NaN,0.289083,0.553279,0.208809,0.065609,0.111157,0.209935,1.378751,2020,NaN,NaN,NaN,NaN
934,Afghanistan,South Asia,153,2.5669,NaN,0.300706,0.356434,0.266052,0.000000,0.001226,0.135235,1.507236,2020,NaN,NaN,NaN,NaN

In [147]:
df_all[df_all["Trust (Government Corruption)"].isnull()]

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual,Year,Lower Confidence Interval,Upper Confidence Interval,Whisker.high,Whisker.low
489,United Arab Emirates,Middle East and North Africa,20,6.774,NaN,2.096,0.776,0.67,0.284,NaN,0.186,2.762,2018,NaN,NaN,NaN,NaN

## Creat a clean dataset for future exploration

In [148]:
df_all.to_csv('data_all.csv')

In [149]:
data_top = df_all[df_all["Happiness Rank"]<=5]
data_top

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual,Year,Lower Confidence Interval,Upper Confidence Interval,Whisker.high,Whisker.low
0,Switzerland,Western Europe,1,7.5870,0.03411,1.396510,1.349510,0.941430,0.665570,0.419780,0.296780,2.517380,2015,NaN,NaN,NaN,NaN
1,Iceland,Western Europe,2,7.5610,0.04884,1.302320,1.402230,0.947840,0.628770,0.141450,0.436300,2.702010,2015,NaN,NaN,NaN,NaN
2,Denmark,Western Europe,3,7.5270,0.03328,1.325480,1.360580,0.874640,0.649380,0.483570,0.341390,2.492040,2015,NaN,NaN,NaN,NaN
3,Norway,Western Europe,4,7.5220,0.03880,1.459000,1.330950,0.885210,0.669730,0.365030,0.346990,2.465310,2015,NaN,NaN,NaN,NaN
4,Canada,North America,5,7.4270,0.03553,1.326290,1.322610,0.905630,0.632970,0.329570,0.458110,2.451760,2015,NaN,NaN,NaN,NaN
158,Denmark,Western Europe,1,7.5260,NaN,1.441780,1.163740,0.795040,0.579410,0.444530,0.361710,2.739390,2016,7.460,7.592,NaN,NaN
159,Switzerland,Western Europe,2,7.5090,NaN,1.527330,1.145240,0.863030,0.585570,0.412030,0.280830,2.694630,2016,7.428,7.590,NaN,NaN
160,Iceland,Western Europe,3,7.5010,NaN,1.426660,1.183260,0.867330,0.566240,0.149750,0.476780,2.831370,2016,7.333,7.669,NaN,NaN
161,Norway,Western Europe,4,7.4980,NaN,1.577440,1.126900,0.795790,0.596090,0.357760,0.378950,2.664650,2016,7.421,7.575,NaN,NaN
162,Finland,Western Europe,5,7.4130,NaN,1.405980,1.134640,0.810910,0.571040,0.410040,0.254920,2.825960,2016,7.351,7.475,NaN,NaN
315,Norway,Western Europe,1,7.5370,NaN,1.616463,1.533524,0.796667,0.635423,0.315964,0.362012,2.277027,2017,NaN,NaN,7.594445,7.479556
316,Denmark,Western Europe,2,7.5220,NaN,1.482383,1.551122,0.792566,0.626007,0.400770,0.355280,2.313707,2017,NaN,NaN,7.581728,7.462272
317,Iceland,Western Europe,3,7.5040,NaN,1.480633,1.610574,0.833552,0.627163,0.153527,0.475540,2.322715,2017,NaN,NaN,7.622030,7.385970
318,Switzerland,Western Europe,4,7.4940,NaN,1.564980,1.516912,0.858131,0.620071,0.367007,0.290549,2.276716,2017,NaN,NaN,7.561772,7.426227
319,Finland,Western Europe,5,7.4690,NaN,1.443572,1.540247,0.809158,0.617951,0.382612,0.245483,2.430182,2017,NaN,NaN,7.527542,7.410458
470,Finland,Western Europe,1,7.6320,NaN,1.305000,1.592000,0.874000,0.681000,0.393000,0.202000,2.585000,2018,NaN,NaN,NaN,NaN
471,Norway,Western Europe,2,7.5940,NaN,1.456000,1.582000,0.861000,0.686000,0.340000,0.286000,2.383000,2018,NaN,NaN,NaN,NaN
472,Denmark,Western Europe,3,7.5550,NaN,1.351000,1.590000,0.868000,0.683000,0.408000,0.284000,2.371000,2018,NaN,NaN,NaN,NaN
473,Iceland,Western Europe,4,7.4950,NaN,1.343000,1.644000,0.914000,0.677000,0.138000,0.353000,2.426000,2018,NaN,NaN,NaN,NaN
474,Switzerland,Western Europe,5,7.4870,NaN,1.420000,1.549000,0.927000,0.660000,0.357000,0.256000,2.318000,2018,NaN,NaN,NaN,NaN
626,Finland,Western Europe,1,7.7690,NaN,1.340000,1.587000,0.986000,0.596000,0.393000,0.153000,2.714000,2019,NaN,NaN,NaN,NaN
627,Denmark,Western Europe,2,7.6000,NaN,1.383000,1.573000,0.996000,0.592000,0.410000,0.252000,2.394000,2019,NaN,NaN,NaN,NaN
628,Norway,Western Europe,3,7.5540,NaN,1.488000,1.582000,1.028000,0.603000,0.341000,0.271000,2.241000,2019,NaN,NaN,NaN,NaN
629,Iceland,Western Europe,4,7.4940,NaN,1.380000,1.624000,1.026000,0.591000,0.118000,0.354000,2.401000,2019,NaN,NaN,NaN,NaN
630,Netherlands,Western Europe,5,7.4880,NaN,1.396000,1.522000,0.999000,0.557000,0.298000,0.322000,2.394000,2019,NaN,NaN,NaN,NaN
782,Finland,Western Europe,1,7.8087,NaN,1.285190,1.499526,0.961271,0.662317,0.477857,0.159670,2.762835,2020,NaN,NaN,NaN,NaN
783,Denmark,Western Europe,2,7.6456,NaN,1.326949,1.503449,0.979333,0.665040,0.495260,0.242793,2.432741,2020,NaN,NaN,NaN,NaN
784,Switzerland,Western Europe,3,7.5599,NaN,1.390774,1.472403,1.040533,0.628954,0.407946,0.269056,2.350267,2020,NaN,NaN,NaN,NaN
785,Iceland,Western Europe,4,7.5045,NaN,1.326502,1.547567,1.000843,0.661981,0.144541,0.362330,2.460688,2020,NaN,NaN,NaN,NaN
786,Norway,Western Europe,5,7.4880,NaN,1.424207,1.495173,1.008072,0.670201,0.434101,0.287985,2.168266,2020,NaN,NaN,NaN,NaN
935,Finland,Western Europe,1,7.8420,NaN,1.446000,1.106000,0.741000,0.691000,0.481000,0.124000,3.253000,2021,NaN,NaN,NaN,NaN
936,Denmark,Western Europe,2,7.6200,NaN,1.502000,1.108000,0.763000,0.686000,0.485000,0.208000,2.868000,2021,NaN,NaN,NaN,NaN
937,Switzerland,Western Europe,3,7.5710,NaN,1.566000,1.079000,0.816000,0.653000,0.413000,0.204000,2.839000,2021,NaN,NaN,NaN,NaN
938,Iceland,Western Europe,4,7.5540,NaN,1.482000,1.172000,0.772000,0.698000,0.170000,0.293000,2.967000,2021,NaN,NaN,NaN,NaN
939,Netherlands,Western Europe,5,7.4640,NaN,1.501000,1.079000,0.753000,0.647000,0.384000,0.302000,2.798000,2021,NaN,NaN,NaN,NaN
1084,Finland,Western Europe,1,7.8210,NaN,1.892000,1.258000,0.775000,0.736000,0.534000,0.109000,2.518000,2022,NaN,NaN,NaN,NaN
1085,Denmark,Western Europe,2,7.6360,NaN,1.953000,1.243000,0.777000,0.719000,0.532000,0.188000,2.226000,2022,NaN,NaN,NaN,NaN
1086,Iceland,Western Europe,3,7.5570,NaN,1.936000,1.320000,0.803000,0.718000,0.191000,0.270000,2.320000,2022,NaN,NaN,NaN,NaN
1087,Switzerland,Western Europe,4,7.5120,NaN,2.026000,1.226000,0.822000,0.677000,0.461000,0.147000,2.153000,2022,NaN,NaN,NaN,NaN
1088,Netherlands,Western Europe,5,7.4150,NaN,1.945000,1.206000,0.787000,0.651000,0.419000,0.271000,2.137000,2022,NaN,NaN,NaN,NaN